### ISSUE TITLE
Failure creating self-signed certificate with the x509 package

### ISSUE THREAD

**Issue by sforshee** [chrishoffman/vault-signer#1]
I'm attempting to use vault-signer to generate a self-signed x509 certificate for an RSA key held in the vault transit secrets engine. A simplified test program can be found at https://gist.github.com/sforshee/f6f1bef6148240929a334d9d867cdc39. When I run the program, it fails trying to verify the signature:

```
2022/03/15 19:43:45 Error creating certificate: x509: signature over certificate returned by signer is invalid: crypto/rsa: verification error
```

The `crypto.Signer` interface expects a digest, which is what the x509 package supplies. But vault-signer does not set `prehashed=true` in the signing request, so the digest is treated as a plaintext. If I modify vault-signer to set `prehashed=true` the certificate verification is successful. This causes the vault-signer tests to fail, however.

**Comment by chrishoffman** [comment]
I vaguely recall this coming up in Vault and a [prehashed](https://www.vaultproject.io/api/secret/transit#prehashed) parameter was added to support this case. It seems like we'll need another toggle in the signer configuration to handle this scenario. Thanks for the reproduction and the gist. I'll try and take a look at this shortly.

**Comment by chrishoffman** [comment]
@sforshee I believe #2 will resolve your issue. Can you give me a quick review and let me know what you think?

**Comment by sforshee** [comment]
Thanks for the quick response! I tested the changes, and they fix the problem I'm having with the x509 package.

**Comment by chrishoffman** [comment]
I tweaked the implementation slightly in #3 but also explored a way to infer if the data passed to Sign is hashed or not in https://github.com/chrishoffman/vault-signer/compare/prehash-from-signeropts. I looked at some Sign implementations and can't tell for sure if this is the appropriate approach or if this approach is consistently applied. Any insight would be helpful but I believe the explicit implementation in #3 will work just fine.

**Comment by sforshee** [comment]
I'm afraid I can't really offer any insight. I don't have any expertise about golang crypto.Signer. I'd never even written more than a few lines of go before last week.

What I can tell you is that the implementations in #3 and in your prehash-from-signeropts branch both seem to work fine for my use case.

**Comment by chrishoffman** [comment]
Thanks again. I ended up going with the third options since I found a few reference implementations that did the right things with SignerOpts. So this ended up being a bug that should require no changes to your original code to work. I added tests for x509 and JWT signing https://github.com/chrishoffman/vault-signer/blob/main/vault_signer_test.go#L121-L190.
